### PR TITLE
Removes the `IGrainWithGuidKey` constraint from `ISyncWorker`.

### LINKED ISSUE #52: Can ISyncWorker omit imposing IGrainWithGuidKey?
The definition
```csharp
public interface ISyncWorker<in TRequest, TResult> : IGrainWithGuidKey
```
imposes the type of key to a grain. Would it be interesting to omit the grain type from the ISyncWorker, or perhaps basing it on a generic `IGrain` (or `IAddressable`, I'm not quite sure what the proper base would be) instead?
```csharp
public interface ISyncWorker<in TRequest, TResult>: IGrain
```
Testing the modification in the SyncWork repo breaks all grainfactory instances, because there is no type system hint what proper overload to choose.
`GrainFactory.GetGrain<ISyncWorker<TestDelaySuccessRequest, TestDelaySuccessResult>>(Guid.NewGuid());` 

I see some options:
- Have a parallel hierarchy ISyncWorkerWithGuidKey<> etc for each of the Orleans grain types
- Have the user name the implementation explicitly like
```csharp
/// <summary>
/// Represents the contract for a SyncWorker grain verifying a password.
/// </summary>
public interface IPasswordVerifierGrain : IPasswordVerifier, ISyncWorker<PasswordVerifierRequest, PasswordVerifierResult>, IGrainWithGuidKey;
```

What are your thoughts on this?

Kind regards,
Hendrik

### PR DESCRIPTION
**Pull request by Kritner**
# Description

**_This is a breaking change to the package_**, but does allow for more control over the implementations of long running grains.

Removes the `IGrainWithGuidKey` constraint from `ISyncWorker`.

`ISyncWorker` was defined as:

```cs
public ISyncWorker<in TRequest, TResult> : IGrainWithGuidKey
```

Now it is defined as:

```cs
public ISyncWorker<in TRequest, TResult> : IGrain
```

This will allow implementations against the base class `SyncWorker<TRequest, TResult>` to specify the key type that fits their needs.

Previously, a "grain interface" was not ***required*** for implementations, now it will certainly make things easier to grok, albeit with an additional interface per long running grain.

Old implementation:

```cs
public class PasswordVerifier : SyncWorker<PasswordVerifierRequest, PasswordVerifierResult>
{
  // ...
}
```

New implementation:

```cs
// now specifying the key type in the grain interface
public interface IPasswordVerifierGrain : ISyncWorker<PasswordVerifierRequest, PasswordVerifierResult>, IGrainWithGuidKey

public class PasswordVerifierGrain : SyncWorker<PasswordVerifierRequest, PasswordVerifierResult>, IPasswordVerifierGrain
{
  // ...
}
```

Old calling code:

```cs
var grain = grainFactory.GetGrain<ISyncWorker<PasswordVerifierRequest, PasswordVerifierResult>>(Guid.NewGuid());
```

New calling code:

```cs
var grain = grainFactory.GetGrain<IPasswordVerifierGrain>(Guid.NewGuid());
```

Fixes #52

## Type of Change

Use an `x` in between the `[ ]` for each line applicable to the type of change for this PR

* [ ] Bug fix
* [x] New Feature
* [x] Documentation
* [x] Code improvement
* [x] Breaking change - if a public API changes, or any change that ***DOES*** or ***MAY*** require a major revision to the NuGet package version due to [semver](https://semver.org/).
* [x] Unit tests
* [x] Code samples
* [ ] Added your repository URL to the readme because you make use of this super cool package! ;)
* [ ] Other

## Describe testing that was performed for your change

Updated existing tests

## Checklist

* [x] Read the https://github.com/OrleansContrib/Orleans.SyncWork/blob/main/CONTRIBUTING.md
* [x] Ran unit tests and ensured they passed
* [x] Added unit tests where applicable
* [x] Referenced an issue where applicable
* [x] Ran `dotnet-format` locally

### CODE REVIEW

**Comment by Kritner** [comment]
@hendrikdevloed this about what you expected?

**Comment by hendrikdevloed** [comment]
Wow that was quick, I'll check today and tomorrow if I can fit this in my program's grain model and give feedback. Thanks!

**Comment by Kritner** [comment]
@hendrikdevloed you good compiling from this branch?  Or do i need to figure out how to get a pre-release package deployed?

**Comment by hendrikdevloed** [comment]
Thanks, I'm fine, I took the branch's source into my project and temporarily removed the NuGet reference.

**Comment by hendrikdevloed** [comment]
A tangential question while I was deriving my grain from SyncWorkerGrain: is there a reasoning behind throwing an exception from `GetWorkStatus()` when the grain has not been started yet, versus returning `NotStarted`?
```csharp
if (_status == SyncWorkStatus.NotStarted)
{
    Logger.LogError("{Method} was in a status of {WorkStatus}", nameof(GetWorkStatus), SyncWorkStatus.NotStarted);
    DeactivateOnIdle();
    throw new InvalidStateException(_status);
}
return Task.FromResult(_status);
```

I ask because I intended to start a long-running task (in my project a sequenceFactoryGrain eventually creates a sequenceGrain, working as a long-running task) in an idempotent way, like
```csharp
ISequenceGrain sequenceGrain = await sequenceFactoryGrain.GetWorkStatus() switch
{
    SyncWorkStatus.NotStarted => await sequenceFactoryGrain.StartWorkAndPollUntilResult(sequence),
    SyncWorkStatus.Running => await sequenceFactoryGrain.ContinueWorkAndPollUntilResult(sequence),
    SyncWorkStatus.Completed => (await sequenceFactoryGrain.GetResult())!,
    SyncWorkStatus.Faulted => throw (await sequenceFactoryGrain.GetException())!,
    _ => throw new NotImplementedException()
};
```
but was surprised by the exception thrown when trying to check the current state.

My intent: If some external non-Orleans API call tries to start the factory to get a grain, but if somehow there is a timeout/cancellation/... and the API retries, I should be able to find out that the sequenceFactoryGrain is already processing and just tag along waiting for the long-running call to complete.
(`ContinueWorkAndPollUntilResult` is the same code as `StartWorkAndPollUntilResult` but without the `Start` call)

PS: do you still actively hang out on the Orleans Discord?

**Comment by Kritner** [comment]
> is there a reasoning behind throwing an exception from GetWorkStatus() when the grain has not been started yet, versus returning NotStarted?

No reasoning - and I'd have no qualms w/ taking that check out

If you want to open an issue about changing the behavior, I could get that rolled into the next nuget package release along w/ #53 and #55

> PS: do you still actively hang out on the Orleans Discord? Otherwise we could take this off-topic thread over there?

I don't really take a look at it much these days, got a bit too noisy, and I'm not actively working w/ Orleans atm.

**Comment by Kritner** [comment]
Just since we had some additional back and forth here - lmk if/when you've evaluated the change and if it's g2g

**Comment by Kritner** [comment]
Yo @hendrikdevloed just wanted to check in to see if you've had a chance to try this out? Was hoping to get this merged in, cuz it's going to have some conflicts with #53

**Comment by hendrikdevloed** [comment]
Hi Russ,

I've managed to run it with a string based key, so I assume it is working. I'm refactoring a part of my application and can't test my new design that uses the different grain key type thoroughly, so I'm not able to confirm with 100% certainty yet.

But if you want to merge it, you definitely have my blessing, it looks fine.

Thanks for the swift fix,
Hendrik

**Pull request merged**
